version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: knowledge_graph_neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      # Authentication
      NEO4J_AUTH: neo4j/knowledge_graph_password
      
      # Memory settings
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G
      
      # Plugins
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      
      # Configuration
      NEO4J_dbms_security_procedures_unrestricted: gds.*,apoc.*
      NEO4J_dbms_security_procedures_allowlist: gds.*,apoc.*
      
      # Logging
      NEO4J_dbms_logs_debug_level: INFO
      
      # Transaction settings
      NEO4J_dbms_transaction_timeout: 60s
      
      # Network settings
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
      NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474
      
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./neo4j.conf:/var/lib/neo4j/conf/neo4j.conf:ro
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p knowledge_graph_password 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Optional: Application container
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: knowledge_graph_app
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: knowledge_graph_password
    ports:
      - "5000:5000"  # Flask API
      - "8888:8888"  # Jupyter
    volumes:
      - ../notebooks:/app/notebooks
      - ../src:/app/src
      - ../examples:/app/examples
    profiles:
      - full  # Only start with: docker-compose --profile full up

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  default:
    name: knowledge_graph_network
