services:
  fluentd:
    image: fluent/fluentd:v1.16-1
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd/fluentd.conf:/fluentd/etc/fluent.conf
    networks:
      - fluentd-network
    depends_on:
      - webhook

  fluentbit:
    build:
      context: .
      dockerfile: fluentbit-custom/Dockerfile
    # ports:
    #   - "8080-8089:8080"  # Map ports for monitoring endpoints (health, metrics, stats)
    depends_on:
      - fluentd
    networks:
      - fluentd-network
    deploy:
      replicas: 10

  webhook:
    image: python:3.9-slim-bookworm
    ports:
      - "3000:3000"
    volumes:
      - ./webhook:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python webhook_server.py"
    networks:
      - fluentd-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - discovery.type="single-node"
      - xpack.security.enabled=false
      - ELASTICPASSWORD="123456"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - fluentd-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - KIBANAPASSWORD="123456"
    ports:
      - "5601:5601"
    networks:
      - fluentd-network
    depends_on:
      - elasticsearch
networks:
  fluentd-network:

#STACK_VERSION=8.7.1