// compeonents/Inbox.tsx
import { Inbox } from "@novu/nextjs";
import "../app/globals.css";
export const metadata = {
  title: "Novu Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode}) {
  // const [filter, setFilter] = useState<FilterStatus>('all');
  return (
    <html lang="en">
      <body>
        <nav className="flex justify-end items-center p-4 gap-4 h-16">
          <Inbox
            applicationIdentifier="aG3MI3KIqBzS"
            subscriber="682ad4798903dafcd0efe3de"
          />
        </nav>
        {children}
      </body>
    </html>
  );
}
